# Generated by Django 4.2.7 on 2023-12-12 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tf2folio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transactions',
            new_name='Transaction',
        ),
    ]
