# Generated by Django 4.2.7 on 2023-12-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tf2folio', '0003_alter_item_owner_alter_item_particle_effect_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_title',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
