# Generated by Django 4.2.7 on 2024-02-09 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tf2folio', '0003_usermarketsettings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='market_settings',
        ),
        migrations.AddField(
            model_name='usermarketsettings',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='market_settings', to=settings.AUTH_USER_MODEL),
        ),
    ]
