# Generated by Django 4.2.7 on 2023-12-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tf2folio', '0004_item_item_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='particle_id',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
