# Generated by Django 4.2.7 on 2023-12-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tf2folio', '0005_item_particle_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='particle_id',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
