# Generated by Django 4.2.7 on 2024-02-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tf2folio', '0005_alter_usermarketsettings_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermarketsettings',
            name='paypal_key_price_dollars',
            field=models.DecimalField(decimal_places=2, default='1.7', max_digits=4),
        ),
        migrations.AlterField(
            model_name='usermarketsettings',
            name='scm_key_price_dollars',
            field=models.DecimalField(decimal_places=2, default='2.2', max_digits=4),
        ),
    ]
