# Generated by Django 4.2.7 on 2024-02-16 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tf2folio', '0006_alter_usermarketsettings_paypal_key_price_dollars_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usermarketsettings',
            name='scm_key_price_dollars',
            field=models.DecimalField(decimal_places=2, default='2.15', max_digits=4),
        ),
    ]
