# Generated by Django 4.2.7 on 2023-12-13 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tf2folio', '0006_alter_item_particle_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='sell_method',
            field=models.CharField(blank=True, choices=[('keys', 'Keys'), ('scm_funds', 'Steam Community Market Funds'), ('paypal', 'PayPal'), ('items', 'TF2 Items')], max_length=30, null=True),
        ),
    ]
