# Generated by Django 4.2.7 on 2023-12-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tf2folio', '0007_transaction_amount_transaction_sell_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='sell_method',
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_method',
            field=models.CharField(choices=[('keys', 'Keys'), ('scm_funds', 'Steam Community Market Funds'), ('paypal', 'PayPal'), ('items', 'TF2 Items')], default=0, max_length=30),
            preserve_default=False,
        ),
    ]
