# Generated by Django 4.2.7 on 2023-12-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tf2folio', '0013_item_sold_value_item_estimated_price_item_sale_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='value',
            name='transaction_type',
        ),
        migrations.AlterField(
            model_name='value',
            name='transaction_method',
            field=models.CharField(choices=[('keys', 'Keys'), ('scm_funds', 'Steam Wallet Funds'), ('paypal', 'PayPal')], max_length=30),
        ),
    ]
