# Generated by Django 4.2.7 on 2023-12-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tf2folio', '0014_remove_value_transaction_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='value',
            name='transaction_method',
            field=models.CharField(choices=[('keys', 'Keys'), ('scm_funds', 'Steam Wallet Funds'), ('paypal', 'PayPal')], default=('keys', 'Keys'), max_length=30),
        ),
    ]
