# Generated by Django 4.2.7 on 2023-12-19 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tf2folio', '0015_alter_value_transaction_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='estimated_price',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estimated_item_value', to='tf2folio.value'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sale_price',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sold_item_value', to='tf2folio.value'),
        ),
    ]
