# Generated by Django 4.2.7 on 2023-12-20 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tf2folio', '0016_alter_item_estimated_price_alter_item_sale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='estimated_price',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimated_item_value', to='tf2folio.value'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sale_price',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sold_item_value', to='tf2folio.value'),
        ),
    ]
