# Generated by Django 4.2.7 on 2023-12-20 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tf2folio', '0017_alter_item_estimated_price_alter_item_sale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_method',
            field=models.CharField(choices=[('keys', 'Keys'), ('scm_funds', 'Steam Wallet Funds'), ('paypal', 'PayPal'), ('items', 'TF2 Items')], default=('keys', 'Keys'), max_length=30),
        ),
    ]
