# Generated by Django 4.2.7 on 2024-01-09 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tf2folio', '0020_alter_user_default_scm_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='purchase_price',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_price_value', to='tf2folio.value'),
        ),
    ]
