# Generated by Django 4.2.7 on 2024-01-09 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tf2folio', '0021_item_purchase_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_value',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_value', to='tf2folio.value'),
        ),
    ]
