# Generated by Django 4.2.7 on 2024-01-09 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tf2folio', '0022_transaction_transaction_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='value',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tf2folio.transaction'),
        ),
        migrations.AlterField(
            model_name='value',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_value', to='tf2folio.item'),
        ),
    ]
