# Generated by Django 4.2.7 on 2024-01-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tf2folio', '0023_value_transaction_alter_value_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_method',
        ),
        migrations.AlterField(
            model_name='value',
            name='transaction_method',
            field=models.CharField(choices=[('keys', 'Keys'), ('scm_funds', 'Steam Wallet Funds'), ('paypal', 'PayPal'), ('items', 'TF2 Items')], default=('keys', 'Keys'), max_length=30),
        ),
    ]
