name: Testing
on: push

jobs:
    test_project:
        runs-on: ubuntu-latest
        services:
          db:
            image: postgres
            env:
              POSTGRES_USER: postgres
              POSTGRES_PASSWORD: postgres
              POSTGRES_DB: postgres

        steps:
            - uses: actions/checkout@v2
            - name: Build and run Docker image
              run: |
                docker build -t tf2folio .
                docker run -d --name tf2folio --network service:db tf2folio
            - name: Run Django unit tests
              run: |
                docker exec tf2folio python3 manage.py migrate
                docker exec tf2folio python3 manage.py test

