name: Testing
on: push

jobs:
    test_project:
        runs-on: ubuntu-latest
        
        steps:
            - uses: actions/checkout@v2
            - name: Build and run Docker image
              run: |
                docker compose up -d
                
            - name: Run Django unit tests
              run: |
                docker exec tf2folio python3 manage.py migrate
                docker exec tf2folio python3 manage.py test

