name: Testing
on: 
  push:
  pull_request:

jobs:
    test_project:
        runs-on: ubuntu-latest
        
        steps:
            - uses: actions/checkout@v2
            - name: Build and run Docker image
              run: |
                docker compose up -d
                
            - name: Run Django unit tests
              run: |
                docker compose exec web python3 manage.py test

